// Code generated by colgen v0.1.3; DO NOT EDIT.
package db

type ExamAnswerList []ExamAnswer

func (ll ExamAnswerList) IndexByQuestionID() map[int]ExamAnswer {
	r := make(map[int]ExamAnswer, len(ll))
	for i := range ll {
		r[ll[i].QuestionID] = ll[i]
	}
	return r
}
