// Code generated by colgen v0.1.3; DO NOT EDIT.
package db

type Questions []Question

func (ll Questions) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll Questions) Index() map[int]Question {
	r := make(map[int]Question, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}
