// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"unicode/utf8"
)

const (
	ErrEmptyValue = "empty"
	ErrMaxLength  = "len"
	ErrWrongValue = "value"
)

func (u User) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(u.Login) > 64 {
		errors[Columns.User.Login] = ErrMaxLength
	}

	if utf8.RuneCountInString(u.Password) > 64 {
		errors[Columns.User.Password] = ErrMaxLength
	}

	if utf8.RuneCountInString(u.AuthKey) > 32 {
		errors[Columns.User.AuthKey] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (c Course) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(c.Title) > 255 {
		errors[Columns.Course.Title] = ErrMaxLength
	}

	if utf8.RuneCountInString(c.AvailabilityType) > 255 {
		errors[Columns.Course.AvailabilityType] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (e Exam) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(e.Status) > 255 {
		errors[Columns.Exam.Status] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (q Question) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(q.QuestionType) > 255 {
		errors[Columns.Question.QuestionType] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (s Student) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(s.Login) > 255 {
		errors[Columns.Student.Login] = ErrMaxLength
	}

	if utf8.RuneCountInString(s.PasswordHash) > 255 {
		errors[Columns.Student.PasswordHash] = ErrMaxLength
	}

	if utf8.RuneCountInString(s.FirstName) > 255 {
		errors[Columns.Student.FirstName] = ErrMaxLength
	}

	if utf8.RuneCountInString(s.LastName) > 255 {
		errors[Columns.Student.LastName] = ErrMaxLength
	}

	if utf8.RuneCountInString(s.Email) > 255 {
		errors[Columns.Student.Email] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (vf VfsFile) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(vf.Title) > 255 {
		errors[Columns.VfsFile.Title] = ErrMaxLength
	}

	if utf8.RuneCountInString(vf.Path) > 255 {
		errors[Columns.VfsFile.Path] = ErrMaxLength
	}

	if utf8.RuneCountInString(vf.MimeType) > 255 {
		errors[Columns.VfsFile.MimeType] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (vf VfsFolder) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(vf.Title) > 255 {
		errors[Columns.VfsFolder.Title] = ErrMaxLength
	}

	return errors, len(errors) == 0
}
