// Code generated by colgen v0.1.3; DO NOT EDIT.
package coursepass

import (
	"courses/pkg/db"
)

func NewCourses(in []db.Course) []Course { return MapP(in, NewCourse) }

func NewExams(in []db.Exam) []Exam { return MapP(in, NewExam) }

func NewQuestions(in []db.Question) []Question { return MapP(in, NewQuestion) }
