// Code generated by zenrpc v2.3.1; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	CourseService struct{ Register, Login, Me string }
}{
	CourseService: struct{ Register, Login, Me string }{
		Register: "register",
		Login:    "login",
		Me:       "me",
	},
}

func (CourseService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Register": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "RegisterRequest",
						Properties: smd.PropertyList{
							{
								Name: "login",
								Type: smd.String,
							},
							{
								Name: "password",
								Type: smd.String,
							},
							{
								Name: "email",
								Type: smd.String,
							},
							{
								Name: "firstName",
								Type: smd.String,
							},
							{
								Name: "lastName",
								Type: smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "RegisterResponse",
					Properties: smd.PropertyList{
						{
							Name: "accessToken",
							Type: smd.String,
						},
						{
							Name: "expiresIn",
							Type: smd.Integer,
						},
						{
							Name: "tokenType",
							Type: smd.String,
						},
					},
				},
			},
			"Login": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "LoginRequest",
						Properties: smd.PropertyList{
							{
								Name: "login",
								Type: smd.String,
							},
							{
								Name: "password",
								Type: smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "LoginResponse",
					Properties: smd.PropertyList{
						{
							Name: "accessToken",
							Type: smd.String,
						},
						{
							Name: "expiresIn",
							Type: smd.Integer,
						},
						{
							Name: "tokenType",
							Type: smd.String,
						},
					},
				},
			},
			"Me": {
				Parameters: []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "MeResponse",
					Properties: smd.PropertyList{
						{
							Name: "studentId",
							Type: smd.Integer,
						},
						{
							Name: "login",
							Type: smd.String,
						},
						{
							Name: "email",
							Type: smd.String,
						},
						{
							Name: "firstName",
							Type: smd.String,
						},
						{
							Name: "lastName",
							Type: smd.String,
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s CourseService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.CourseService.Register:
		var args = struct {
			Req RegisterRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Register(ctx, args.Req))

	case RPC.CourseService.Login:
		var args = struct {
			Req LoginRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Login(ctx, args.Req))

	case RPC.CourseService.Me:
		resp.Set(s.Me(ctx))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
